export type CommodityTier = 'tier1' | 'tier2';
export type DataSource = 'EIA' | 'FRED' | 'Premium';

export interface Commodity {
  id: string;
  name: string;
  shortName: string;
  tier: CommodityTier;
  category: string;
  unit: string;
  dataSource: DataSource;
  badgeLabel: string;
  badgeColor: 'green' | 'gold';
  description: string;
  feedstocks?: [string, string];
  eiaSeriesId?: string;
  fredSeriesId?: string;
  basePrice: number;
  volatility: number;
}

export const COMMODITIES: Commodity[] = [
  // ── Tier 1: Real API data ──
  {
    id: 'crude-oil',
    name: 'Crude Oil (WTI)',
    shortName: 'WTI Crude',
    tier: 'tier1',
    category: 'Energy',
    unit: '$/bbl',
    dataSource: 'EIA',
    badgeLabel: 'Gov: EIA',
    badgeColor: 'green',
    description: 'West Texas Intermediate crude oil spot price (Cushing, OK)',
    eiaSeriesId: 'RWTC',
    basePrice: 78.5,
    volatility: 3.2,
  },
  {
    id: 'natural-gas',
    name: 'Natural Gas (Henry Hub)',
    shortName: 'Nat Gas HH',
    tier: 'tier1',
    category: 'Energy',
    unit: '$/MMBtu',
    dataSource: 'EIA',
    badgeLabel: 'Gov: EIA',
    badgeColor: 'green',
    description: 'Henry Hub natural gas spot price',
    eiaSeriesId: 'RNGWHHD',
    basePrice: 2.85,
    volatility: 0.35,
  },
  {
    id: 'gasoline',
    name: 'Gasoline (RBOB)',
    shortName: 'RBOB Gasoline',
    tier: 'tier1',
    category: 'Energy',
    unit: '$/gal',
    dataSource: 'EIA',
    badgeLabel: 'Gov: EIA',
    badgeColor: 'green',
    description: 'Reformulated blendstock for oxygenate blending (NY Harbor)',
    eiaSeriesId: 'EER_EPMRR_PF4_RGC_DPG',
    basePrice: 2.65,
    volatility: 0.12,
  },
  {
    id: 'ethanol',
    name: 'Ethanol',
    shortName: 'Ethanol',
    tier: 'tier1',
    category: 'Bio-Chemicals',
    unit: '$/gal',
    dataSource: 'FRED',
    badgeLabel: 'Gov: FRED',
    badgeColor: 'green',
    description: 'Fuel ethanol spot price (Chicago)',
    fredSeriesId: 'APU000074714',
    basePrice: 1.72,
    volatility: 0.08,
  },
  {
    id: 'naphtha',
    name: 'Naphtha',
    shortName: 'Naphtha',
    tier: 'tier1',
    category: 'Petrochemicals',
    unit: '$/MT',
    dataSource: 'FRED',
    badgeLabel: 'Gov: FRED',
    badgeColor: 'green',
    description: 'Naphtha spot price (Far East/Asia)',
    fredSeriesId: 'PNAPHTHAUSDM',
    basePrice: 612,
    volatility: 28,
  },
  {
    id: 'methanol',
    name: 'Methanol',
    shortName: 'Methanol',
    tier: 'tier1',
    category: 'Chemicals',
    unit: '$/MT',
    dataSource: 'FRED',
    badgeLabel: 'Gov: FRED',
    badgeColor: 'green',
    description: 'Methanol contract price (Europe)',
    fredSeriesId: 'PMETUSDM',
    basePrice: 375,
    volatility: 18,
  },
  {
    id: 'caustic-soda',
    name: 'Caustic Soda (NaOH)',
    shortName: 'Caustic Soda',
    tier: 'tier1',
    category: 'Chlor-Alkali',
    unit: '$/MT',
    dataSource: 'FRED',
    badgeLabel: 'Gov: FRED',
    badgeColor: 'green',
    description: 'Sodium hydroxide (50% solution) price index',
    fredSeriesId: 'WPU0613020101',
    basePrice: 480,
    volatility: 22,
  },
  {
    id: 'liquid-chlorine',
    name: 'Liquid Chlorine',
    shortName: 'Chlorine',
    tier: 'tier1',
    category: 'Chlor-Alkali',
    unit: '$/MT',
    dataSource: 'FRED',
    badgeLabel: 'Gov: FRED',
    badgeColor: 'green',
    description: 'Chlorine (liquefied) producer price index',
    fredSeriesId: 'WPU0613040101',
    basePrice: 265,
    volatility: 14,
  },
  {
    id: 'benzene',
    name: 'Benzene',
    shortName: 'Benzene',
    tier: 'tier1',
    category: 'Aromatics',
    unit: '$/MT',
    dataSource: 'FRED',
    badgeLabel: 'Gov: FRED',
    badgeColor: 'green',
    description: 'Benzene spot price (US Gulf Coast)',
    fredSeriesId: 'PBANSOPUSDM',
    basePrice: 820,
    volatility: 45,
  },

  // ── Tier 2: Premium / Opaque Data ──
  {
    id: 'cpe',
    name: 'Chlorinated Polyethylene (CPE)',
    shortName: 'CPE',
    tier: 'tier2',
    category: 'Polymers',
    unit: '$/MT',
    dataSource: 'Premium',
    badgeLabel: 'Premium Proxy',
    badgeColor: 'gold',
    description: 'CPE resin market price (China/Asia export)',
    feedstocks: ['Caustic Soda', 'Ethylene'],
    basePrice: 1150,
    volatility: 55,
  },
  {
    id: 'cumene',
    name: 'Cumene',
    shortName: 'Cumene',
    tier: 'tier2',
    category: 'Aromatics',
    unit: '$/MT',
    dataSource: 'Premium',
    badgeLabel: 'Premium Proxy',
    badgeColor: 'gold',
    description: 'Cumene (isopropylbenzene) contract price',
    feedstocks: ['Benzene', 'Propylene'],
    basePrice: 940,
    volatility: 42,
  },
  {
    id: 'acrylonitrile',
    name: 'Acrylonitrile (ACN)',
    shortName: 'ACN',
    tier: 'tier2',
    category: 'Petrochemicals',
    unit: '$/MT',
    dataSource: 'Premium',
    badgeLabel: 'Premium Proxy',
    badgeColor: 'gold',
    description: 'Acrylonitrile spot/contract price',
    feedstocks: ['Propylene', 'Natural Gas'],
    basePrice: 1380,
    volatility: 65,
  },
  {
    id: 'acetone',
    name: 'Acetone',
    shortName: 'Acetone',
    tier: 'tier2',
    category: 'Solvents',
    unit: '$/MT',
    dataSource: 'Premium',
    badgeLabel: 'Premium Proxy',
    badgeColor: 'gold',
    description: 'Acetone solvent market price (US)',
    feedstocks: ['Cumene', 'Benzene'],
    basePrice: 680,
    volatility: 32,
  },
  {
    id: 'acetic-acid',
    name: 'Acetic Acid (Glacial)',
    shortName: 'Acetic Acid',
    tier: 'tier2',
    category: 'Chemicals',
    unit: '$/MT',
    dataSource: 'Premium',
    badgeLabel: 'Premium Proxy',
    badgeColor: 'gold',
    description: 'Glacial acetic acid industrial grade',
    feedstocks: ['Methanol', 'Natural Gas'],
    basePrice: 590,
    volatility: 28,
  },
  {
    id: 'acetonitrile',
    name: 'Acetonitrile (MeCN)',
    shortName: 'Acetonitrile',
    tier: 'tier2',
    category: 'Solvents',
    unit: '$/MT',
    dataSource: 'Premium',
    badgeLabel: 'Premium Proxy',
    badgeColor: 'gold',
    description: 'HPLC/pharma-grade acetonitrile price',
    feedstocks: ['Acetic Acid', 'Natural Gas'],
    basePrice: 1850,
    volatility: 90,
  },
  {
    id: 'caustic-potash',
    name: 'Caustic Potash (KOH)',
    shortName: 'KOH',
    tier: 'tier2',
    category: 'Chemicals',
    unit: '$/MT',
    dataSource: 'Premium',
    badgeLabel: 'Premium Proxy',
    badgeColor: 'gold',
    description: 'Potassium hydroxide (90% flake)',
    feedstocks: ['Caustic Soda', 'Natural Gas'],
    basePrice: 720,
    volatility: 35,
  },
  {
    id: 'mixed-xylene',
    name: 'Mixed Xylene',
    shortName: 'Mixed Xylene',
    tier: 'tier2',
    category: 'Aromatics',
    unit: '$/MT',
    dataSource: 'Premium',
    badgeLabel: 'Premium Proxy',
    badgeColor: 'gold',
    description: 'Mixed xylene spot price (Asia/US)',
    feedstocks: ['Benzene', 'Naphtha'],
    basePrice: 750,
    volatility: 36,
  },
  {
    id: 'toluene',
    name: 'Toluene',
    shortName: 'Toluene',
    tier: 'tier2',
    category: 'Aromatics',
    unit: '$/MT',
    dataSource: 'Premium',
    badgeLabel: 'Premium Proxy',
    badgeColor: 'gold',
    description: 'Toluene spot price (US Gulf Coast)',
    feedstocks: ['Benzene', 'Naphtha'],
    basePrice: 710,
    volatility: 34,
  },
  {
    id: 'ethylene',
    name: 'Ethylene',
    shortName: 'Ethylene',
    tier: 'tier2',
    category: 'Olefins',
    unit: '$/MT',
    dataSource: 'Premium',
    badgeLabel: 'Premium Proxy',
    badgeColor: 'gold',
    description: 'Ethylene contract price (US Gulf Coast)',
    feedstocks: ['Natural Gas', 'Naphtha'],
    basePrice: 960,
    volatility: 48,
  },
  {
    id: 'propylene',
    name: 'Propylene',
    shortName: 'Propylene',
    tier: 'tier2',
    category: 'Olefins',
    unit: '$/MT',
    dataSource: 'Premium',
    badgeLabel: 'Premium Proxy',
    badgeColor: 'gold',
    description: 'Polymer-grade propylene (US)',
    feedstocks: ['Natural Gas', 'Naphtha'],
    basePrice: 890,
    volatility: 44,
  },
];

export const CATEGORIES = [...new Set(COMMODITIES.map((c) => c.category))];

export function getCommodityById(id: string): Commodity | undefined {
  return COMMODITIES.find((c) => c.id === id);
}
